server:
  port: 2002
  context-path: /
  
eureka: 
  instance:
    hostname: eureka2002.school.com #eureka注册中心实例名称
  client: 
    register-with-eureka: false     #false 由于该应用为注册中心，所以设置为false,代表不向注册中心注册自己。
    fetch-registry: false     #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url: 
       defaultZone: http://eureka2001.school.com:2001/eureka/,http://eureka2003.school.com:2003/eureka/ # 集群
       #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka注册中心交互的地址，查询服务和注册服务用到