server:
  port: 1004
  context-path: /
 
# 数据源配置
spring:
  application:
    name: bookservice-book
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springcloud
    username: root
    password: ROOT
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: bookservice-book  #客户端服务名
    #instance-id: bookservice-book:1001 #客户端实例名称
    instance-id: bookservice-book-hystrix:1004 #客户端实例名称
    prefer-ip-address: true #显示IP
  client: 
    service-url: 
      #defaultZone: http://localhost:2001/eureka   #把服务注册到eureka注册中心
      defaultZone: http://eureka2001.school.com:2001/eureka/,http://eureka2002.school.com:2002/eureka/,http://eureka2003.school.com:2003/eureka/ # 集群
info: 
   groupId: $project.groupId$
   artifactId: $project.artifactId$
   version: $project.version$
   负责人: 张三
   联系电话: 110
hystrix:
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 3000