server:
  port: 91
  context-path: /
eureka:
  client:
    register-with-eureka: false #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url: 
      defaultZone: http://eureka2001.school.com:2001/eureka/,http://eureka2002.school.com:2002/eureka/,http://eureka2003.school.com:2003/eureka/
turbine:
  app-config: bookservice-book   # 指定要监控的应用名称
  clusterNameExpression: "'default'" #表示集群的名字为default

spring:
  application:
    name: turbine