server:
  port: 80
  context-path: /
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 9000
hystrix:
 command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
eureka:
  client:
    register-with-eureka: false #false 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    service-url: 
      defaultZone: http://eureka2001.school.com:2001/eureka/,http://eureka2002.school.com:2002/eureka/,http://eureka2003.school.com:2003/eureka/