package com.school.pojo;

import java.util.Date;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.name
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publish
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    private String publish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publishdate
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    private Date publishdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.page
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    private Integer page;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.content
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.name
     *
     * @return the value of book.name
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.name
     *
     * @param name the value for book.name
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author
     *
     * @return the value of book.author
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author
     *
     * @param author the value for book.author
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publish
     *
     * @return the value of book.publish
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    public String getPublish() {
        return publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publish
     *
     * @param publish the value for book.publish
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    public void setPublish(String publish) {
        this.publish = publish == null ? null : publish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publishdate
     *
     * @return the value of book.publishdate
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    public Date getPublishdate() {
        return publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publishdate
     *
     * @param publishdate the value for book.publishdate
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    public void setPublishdate(Date publishdate) {
        this.publishdate = publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.page
     *
     * @return the value of book.page
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    public Integer getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.page
     *
     * @param page the value for book.page
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    public void setPage(Integer page) {
        this.page = page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.content
     *
     * @return the value of book.content
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.content
     *
     * @param content the value for book.content
     *
     * @mbg.generated Thu Aug 01 16:41:30 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}